plot(crSpman)
ls
ls()
names(table)
plot(table)
plot(log1p(table$chp_mp), log1p(chp_gen))
plot(log1p(table$chp_mp), log1p(table$chp_gen))
plot(table$chp_mp, table$chp_gen)
plot(log1p(table$chp_mp), log1p(table$chp_gen))
qqnorm(table$chp_mp)
qqnorm(log1p(table$chp_mp))
summary(table$chp_mp)
quantile(table$chp_mp, .9)
quantile(table$chp_mp, .99\)
quantile(table$chp_mp, .99)
t <- table[table$chp_mp <= 1.32, ]
summary(t)
qqnorm(chp_mp)
qqnorm(t$chp_mp)
qqnorm(log1p(t$chp_mp)
qqnorm(log1p(t$chp_mp))
rjac <- read.table('~/Documents/git/rupak/scripts/reports/jd_anal.rpt', sep = '|', header = T)
summary(rjac)
lag <- read.table('~/Documents/git/rupak/scripts/reports/lag.rpt', sep = '|', header = T)
summary(lag)
summary(lag$lag[lag$stage == 'mp'])
lag$lag[lag$stage == 'mp']
lag$lag[lag$stage == 'mp', ]
lag[lag$stage == 'mp', ]
summary(lag$lag[lag$stage eq 'mp'])
rm(lag)
rplag <- read.table('~/Documents/git/rupak/scripts/reports/rp_lag.rpt', sep = '|', header = T)
mplag <- read.table('~/Documents/git/rupak/scripts/reports/mp_lag.rpt', sep = '|', header = T)
summary(rplag)
summary(mplag)
wilcox.test(mplag$lag, rplag$lag)
qqnorm(rplag$lag)
qqnorm(mplag$lag)
boxplot(rplag$lag+1, mplag$lag+1, log = 'y')
length(rplag$lag)
length(mplag$lag)
